# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "nerdondon-hopscotch"
authors = ["nerdondon"]
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.8.0"
rand_distr = "0.4.0"

[dev-dependencies]
pretty_assertions = "0.7.0"
